
export const GET_NEWS = 'GET_NEWS'; 
export const GET_BUSINESS_NEWS = 'GET_BUSINESS_NEWS'; 
export const GET_ENTERTAINMENT_NEWS = 'GET_ENTERTAINMENT_NEWS'; 
export const GET_TECHNOLOGY_NEWS = 'GET_TECHNOLOGY_NEWS'; 
export const GET_HEALTH_NEWS = 'GET_HEALTH_NEWS'; 
export const GET_SCIENCE_NEWS = 'GET_SCIENCE_NEWS'; 
export const GET_SPORT_NEWS = 'GET_SPORT_NEWS'; 
export const GET_MORE_NEWS = 'GET_MORE_NEWS'; 
export const GET_MORE_BUSINESS_NEWS = 'GET_MORE_BUSINESS_NEWS'; 
export const GET_MORE_ENTERTAINMENT_NEWS = 'GET_MORE_ENTERTAINMENT_NEWS'; 
export const GET_MORE_TECHNOLOGY_NEWS = 'GET_MORE_TECHNOLOGY_NEWS'; 
export const GET_MORE_HEALTH_NEWS = 'GET_MORE_HEALTH_NEWS'; 
export const GET_MORE_SCIENCE_NEWS = 'GET_MORE_SCIENCE_NEWS'; 
export const GET_MORE_SPORT_NEWS = 'GET_MORE_SPORT_NEWS'; 