
export const GET_ALLCHAMPIONAT = 'GET_ALLCHAMPIONAT'; 
export const GET_ENGLAND_NEWS = 'GET_ENGLAND_NEWS'; 
export const GET_ITALY_NEWS = 'GET_ITALY_NEWS'; 
export const GET_SPAIN_NEWS = 'GET_SPAIN_NEWS'; 
export const GET_GERMANY_NEWS = 'GET_GERMANY_NEWS'; 
export const GET_FRANCE_NEWS = 'GET_FRANCE_NEWS'; 
export const GET_NETHERLANDS_NEWS = 'GET_NETHERLANDS_NEWS'; 
export const GET_MORE_ALLMATCHES = 'GET_MORE_ALLMATCHES'; 
export const GET_MORE_ENGLAND = 'GET_MORE_BUSINESS_NEWS'; 
export const GET_MORE_ITALY = 'GET_MORE_ENTERTAINMENT_NEWS'; 
export const GET_MORE_SPAIN = 'GET_MORE_SPAIN'; 
export const GET_MORE_GERMANY = 'GET_MORE_GERMANY'; 
export const GET_MORE_FRANCE = 'GET_MORE_FRANCE'; 
export const GET_MORE_NETHERLANDS = 'GET_MORE_NETHERLANDS'; 